name: 'tauri-test'
on: [pull_request, push]

jobs:
  test-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - release_for: Linux
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu

          - release_for: Windows
            os: windows-latest
            target: x86_64-pc-windows-msvc

          - release_for: macOS
            os: macOS-latest
            target: aarch64-apple-darwin

    runs-on: ${{ matrix.platform.os }}
    steps:
      - uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: install cross
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: ${{ matrix.platform.command }}
          target: ${{ matrix.platform.target }}
          args: "--locked --release"
          strip: true
      - name: install dependencies (ubuntu only)
        if: matrix.platform.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
      - name: install frontend dependencies
        run: npm install
      - name: run build script
        run: ./src-tauri/build_resources.sh
      - uses: tauri-apps/tauri-action@v0

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
